version: '3.4'

networks:
  proxy:
    external: true

services:
  html5-to-pdf-with-Puppeteer:
    image: s3pweb/html5-to-pdf-with-Puppeteer:IMAGE_TAG

    networks:
      - proxy

    configs:
      - source: html5-to-pdf-with-Puppeteer.env
        target: /usr/local/app/.env

    deploy:
      mode: replicated
      replicas: 1

      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 30s

      restart_policy:
        # no / any / on-failure
        condition: any
        delay: 30s

      resources:
        limits:
          memory: 500M

      labels:
        # Traefik 2
        traefik.enable: 'true'
        traefik.docker.network: proxy
        traefik.http.services.html5-to-pdf-with-Puppeteer.loadbalancer.server.port: 3000
        # Traefik 2 - external
        traefik.http.routers.html5-to-pdf-with-Puppeteer.rule: Host("html5-to-pdf-with-Puppeteer.s3pweb.xyz")
        traefik.http.routers.html5-to-pdf-with-Puppeteer.tls: 'true'
        traefik.http.routers.html5-to-pdf-with-Puppeteer.middlewares: traefik-bureau-ipwhitelist@docker, authorization-100-ratelimit@docker
        # Traefik 2 - internal
        traefik.http.routers.html5-to-pdf-with-Puppeteer-internal.rule: Host("html5-to-pdf-with-Puppeteer.s3pweb.xyz") && (PathPrefix("/metrics"))
        traefik.http.routers.html5-to-pdf-with-Puppeteer-internal.tls: 'true'
        traefik.http.routers.html5-to-pdf-with-Puppeteer-internal.middlewares: traefik-localhost-ipwhitelist@docker
        # Prometheus Swarm
        prometheus-job: html5-to-pdf-with-Puppeteer
        prometheus-port: 3000
        prometheus-scrape-network: proxy
        prometheus-env: preprod

configs:
  html5-to-pdf-with-Puppeteer.env:
    external: true
